package org.dataone.integration;

public class TestIterationEndingException extends Exception
{
    /**
     * auto-generated by eclipse
     */
    private static final long serialVersionUID = 5496467831748815597L;

    public TestIterationEndingException(String message)
    {
        super(message);
    }

    public TestIterationEndingException(String message, Exception cause) {
        super(message,cause);
    }
}
